### PR TITLE
[release-v1.0] :detective: some more tests for KafkaSink enabled

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

### CODE REVIEW

**Comment by matzew** [comment]
/hold

let's get https://github.com/openshift-knative/eventing-kafka-broker/pull/48  in first

**Comment by matzew** [comment]
/unhold

rebased @pierDipi

**Review by pierDipi — APPROVED** [review]
/lgtm

It just works ?! :man_dancing:

**Pull request merged**
