### PR TITLE
[release-v1.0] Golang 1.17 container image

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

backport of https://github.com/openshift-knative/eventing-kafka-broker/pull/29

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/retest

**Comment by matzew** [comment]
@pierDipi the tests are known to fail, atm (not yet had time for work here)

I merge manually....

**Pull request merged**
