### PR TITLE
Update community files (#3617)

### PR DESCRIPTION
**Pull request by serverless-qe**
Signed-off-by: Knative Automation <automation@knative.team>

### CODE REVIEW

**Comment by creydr** [comment]
```
"message": "Referenced \"ClusterIssuer\" not found: clusterissuer.cert-manager.io \"knative-eventing-ca-issuer\" not found",
```
same issue as https://github.com/openshift-knative/eventing/pull/490#issuecomment-1916290007

**Comment by creydr** [comment]
@pierDipi I guess we need https://github.com/openshift-knative/eventing/pull/513/files#diff-8d4780ca239f8b787f8e8831ea33becadb5238ceabc0b59b55e8ce4d7c679e39R104-R129 here too, or do we have some integration of this into SO?

**Comment by creydr** [comment]
Currently fails with:
```
error: timed out waiting for the condition on deployments/cert-manager-webhook
error: timed out waiting for the condition on deployments/cert-manager
```

Addressed in https://github.com/openshift-knative/serverless-operator/pull/2483

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
