### PR TITLE
[release-v1.3] Backport secret finalizer 1.3

### PR DESCRIPTION
**Pull request by matzew**
Like https://github.com/openshift-knative/eventing-kafka-broker/pull/315 but for 1.3

### CODE REVIEW

**Comment by matzew** [comment]
```
        Message:failed to add finalizer to Secret eventing-e2e8/broker-auth: secrets "broker-auth" is forbidden: User "system:serviceaccount:knative-eventing:kafka-controller" cannot update resource "secrets" in API group "" in the namespace "eventing-e2e8"
```

well...

**Comment by matzew** [comment]
@pierDipi WTF... I have the RBAC right for this ...

what am I not seeing here ? :sweat_smile:

**Comment by matzew** [comment]
Merging: The RBAC is set, I fear that some of the applied yaml is not correct.

Will debug on a different PR , otherwise, I will revert the merge...

**Review by pierDipi — COMMENTED** [review]
Isn't the rbac on which to apply finalizers `secrets/finalizers`?

**Pull request merged**
