### PR TITLE
[release-1.14] Expose OIDC audience of KafkaSink in its status

### PR DESCRIPTION
**Pull request by creydr**
Same as https://github.com/openshift-knative/eventing-kafka-broker/pull/1162 but for 1.14

### CODE REVIEW

**Comment by creydr** [comment]
needs https://github.com/openshift-knative/serverless-operator/pull/2834

**Comment by creydr** [comment]
```
error: unable to locate any images in image streams, local docker images with name "$GO_RUNTIME"
```
Needs https://github.com/openshift-knative/serverless-operator/pull/2835

**Comment by pierDipi** [comment]
```

    certificate.go:165: Failed to get certificate knative-eventing/kafka-sink-ingress-server-tls: certificates.cert-manager.io "kafka-sink-ingress-server-tls" not found
```

**Comment by pierDipi** [comment]
there is something wrong with certificates

**Comment by creydr** [comment]
> ```
> 
>     certificate.go:165: Failed to get certificate knative-eventing/kafka-sink-ingress-server-tls: certificates.cert-manager.io "kafka-sink-ingress-server-tls" not found
> ```

Seems nothing from SOs [eventing-kafka-tls-networking.yaml](https://github.com/openshift-knative/serverless-operator/blob/main/knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-tls-networking.yaml) is applied:

```
grep "Failed to get certificate" build-log.txt 
    certificate.go:165: Failed to get certificate knative-eventing/kafka-sink-ingress-server-tls: certificates.cert-manager.io "kafka-sink-ingress-server-tls" not found
    certificate.go:165: Failed to get certificate knative-eventing/kafka-channel-ingress-server-tls: certificates.cert-manager.io "kafka-channel-ingress-server-tls" not found
    certificate.go:165: Failed to get certificate knative-eventing/kafka-broker-ingress-server-tls: certificates.cert-manager.io "kafka-broker-ingress-server-tls" not found
    certificate.go:165: Failed to get certificate knative-eventing/kafka-sink-ingress-server-tls: certificates.cert-manager.io "kafka-sink-ingress-server-tls" not found
    certificate.go:165: Failed to get certificate knative-eventing/kafka-channel-ingress-server-tls: certificates.cert-manager.io "kafka-channel-ingress-server-tls" not found
    certificate.go:165: Failed to get certificate knative-eventing/kafka-broker-ingress-server-tls: certificates.cert-manager.io "kafka-broker-ingress-server-tls" not found
```

**Comment by creydr** [comment]
> Seems nothing from SOs [eventing-kafka-tls-networking.yaml](https://github.com/openshift-knative/serverless-operator/blob/main/knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-tls-networking.yaml) is applied:
> 
> ```
> grep "Failed to get certificate" build-log.txt 
>     certificate.go:165: Failed to get certificate knative-eventing/kafka-sink-ingress-server-tls: certificates.cert-manager.io "kafka-sink-ingress-server-tls" not found
>     certificate.go:165: Failed to get certificate knative-eventing/kafka-channel-ingress-server-tls: certificates.cert-manager.io "kafka-channel-ingress-server-tls" not found
>     certificate.go:165: Failed to get certificate knative-eventing/kafka-broker-ingress-server-tls: certificates.cert-manager.io "kafka-broker-ingress-server-tls" not found
>     certificate.go:165: Failed to get certificate knative-eventing/kafka-sink-ingress-server-tls: certificates.cert-manager.io "kafka-sink-ingress-server-tls" not found
>     certificate.go:165: Failed to get certificate knative-eventing/kafka-channel-ingress-server-tls: certificates.cert-manager.io "kafka-channel-ingress-server-tls" not found
>     certificate.go:165: Failed to get certificate knative-eventing/kafka-broker-ingress-server-tls: certificates.cert-manager.io "kafka-broker-ingress-server-tls" not found
> ```

https://github.com/openshift-knative/serverless-operator/pull/2841 should help

**Pull request merged**
