### PR TITLE
[release-1.1] Do not delete finalizer until the probe returns status not ready

### PR DESCRIPTION
**Pull request by matzew**
bringing https://github.com/knative-sandbox/eventing-kafka-broker/pull/1883  to midstream

### CODE REVIEW

**Comment by matzew** [comment]
@pierDipi seen this ?

**Comment by pierDipi** [comment]
Yes, same as the other one
```
panic: test timed out after 30m0s
```

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
