### PR TITLE
SRVKE-1463: [release-v1.8] Exclude slf4j-jboss-logmanager from quarkus-vertx for logging (#2934)

### PR DESCRIPTION
**Pull request by pierDipi**
Backport https://github.com/knative-sandbox/eventing-kafka-broker/commit/725c45db2c3949c654bbf20482bc79179110049f

### CODE REVIEW

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
Logs are back: see [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_eventing-kafka-broker/691/pull-ci-openshift-knative-eventing-kafka-broker-release-v1.8-410-test-e2e-aws-ocp-410/1658847861921550336/artifacts/test-e2e-aws-ocp-410/knative-must-gather/artifacts/gather-knative/quay-io-openshift-knative-must-gather-sha256-f1cd829ea23838ac3e9b7e3a42269ea34a32e7af6a5465f9d5d21a3caf3ce446/knative-eventing/pods/kafka-broker-dispatcher-5ff5b9f57c-c6tfv.log)

**Pull request merged**
