### PR TITLE
Update eventing nightly (#3713)

### PR DESCRIPTION
**Pull request by serverless-qe**
bumping knative.dev/eventing 97e91c5...d1ce94e:
  > d1ce94e [main] Upgrade to latest dependencies (# 7702)
  > bb2c03b Add rekt test for containersource autocreate (# 7640)

Signed-off-by: Knative Automation <automation@knative.team>

### CODE REVIEW

**Comment by creydr** [comment]
`No clusters in pool are ready to be claimed `
/retest

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
