### PR TITLE
[release-v1.4] Custom error extension prefix 

### PR DESCRIPTION
**Pull request by matzew**
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2657

### CODE REVIEW

**Comment by matzew** [comment]
/assign @pierDipi 
This is ready for review

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
```
  *[2022-09-19T13:14:36Z]NoClusters: No clusters in pool are ready to be claimed 

```

/retest

**Comment by matzew** [comment]
```
  *[2022-09-20T03:32:28Z]NoClusters: No clusters in pool are ready to be claimed 
```

this is really annoying ...

**Pull request merged**
