### PR TITLE
[release-1.12] Add OIDC support

### PR DESCRIPTION
**Pull request by creydr**
Backport of the OIDC bits from EKB upstream main.

+ update of encryption/auth tests to run OIDC tests too (21053d4ade7caac93821739f2418c8c080c7b077)

### CODE REVIEW

**Comment by creydr** [comment]
Tests are failing (at least) because we deploy eventing-core 1.11, which does not support OIDC yet (e.g. missing audience field in broker CRD)...

**Comment by creydr** [comment]
/hold
as WIP

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
