### PR TITLE
:lipstick: making argument final (#3490)

### PR DESCRIPTION
**Pull request by serverless-qe**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

### CODE REVIEW

**Comment by Cali0707** [comment]
> ```
>         --- FAIL: TestChannelSpec/InMemoryChannel-messaging.knative.dev/v1/Channel_spec_allows_subscribers (6.57s)
> FAIL test/e2e_channel/conformance.TestChannelSpec/InMemoryChannel-messaging.knative.dev/v1/Channel_spec_allows_subscribers (6.57s)
> ```
> 
> @Cali0707 do you have a fix for this here available too? Otherwise I can check later these days

@creydr I'm not familiar on how the midstream tests/sync works. Is it just running the existing tests from upstream? If so, would the fix we made there not also work here?

**Comment by creydr** [comment]
Fix for reconciler tests should be in https://github.com/openshift-knative/eventing-kafka-broker/pull/910

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
