### PR TITLE
[release-v1.2] Support legacy KafkaChannel secret format

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2224

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
Usual KafkaSource flake
/retest

**Comment by aliok** [comment]
/lgtm
/hold

@mgencur Would you like to test it?

**Comment by aliok** [comment]
Verified with the instructions at https://github.com/knative-sandbox/eventing-kafka-broker/issues/2213 locally

**Pull request merged**
