### PR TITLE
Change release build order (#2449)

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by pierDipi** [comment]
@matzew there is real problem here

**Comment by pierDipi** [comment]
The issue was https://github.com/openshift-knative/serverless-operator/pull/1671, let's see now

**Comment by pierDipi** [comment]
Another fix for release-next: https://github.com/openshift-knative/eventing-kafka-broker/pull/370

**Comment by pierDipi** [comment]
Another fix for release-next: https://github.com/openshift-knative/eventing-kafka-broker/pull/372

**Comment by pierDipi** [comment]
Another fix to be pushed upstream https://github.com/openshift-knative/eventing-kafka-broker/pull/373

**Comment by pierDipi** [comment]
Fix pushed upstream https://github.com/knative-sandbox/eventing-kafka-broker/pull/2495/files, @matzew PTAL

**Comment by aliok** [comment]
To be fixed by https://github.com/openshift-knative/eventing-kafka-broker/pull/380

**Comment by pierDipi** [comment]
Working on it in another PR to avoid the bot to override changes: https://github.com/openshift-knative/eventing-kafka-broker/pull/441

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
