### PR TITLE
[release-v1.3] Adding new target for rekt tests

### PR DESCRIPTION
**Pull request by matzew**
ADding new target for rekt tests

### CODE REVIEW

**Comment by matzew** [comment]
/hold

let's merge this after:
https://github.com/openshift-knative/eventing-kafka-broker/pull/236

**Review by pierDipi — APPROVED** [review]
The other PR is in, can you rebase?

**Comment by matzew** [comment]
@pierDipi I just rebased this one too

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
