### PR TITLE
[release-v1.3] Add kafka channel and related changes from upstream

### PR DESCRIPTION
**Pull request by pierDipi**
Similar to https://github.com/openshift-knative/eventing-kafka-broker/pull/221 but for the 1.3 branch

See individual commits for details.

### CODE REVIEW

**Comment by pierDipi** [comment]
Blocked by https://github.com/openshift/release/pull/28027

**Comment by pierDipi** [comment]
```
ERRO[2022-04-21T11:24:22Z] Failed to load arguments.                     error=failed to load configuration: got unexpected http 404 status code from configresolver: failed to get config: could not find any config for branch release-v1.3 on repo openshift-knative/eventing-kafka-broker
```
stale caches?

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
