### PR TITLE
[release-0.26] Add Broker Upgrade Tests

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick of: https://github.com/knative-sandbox/eventing-kafka-broker/pull/1573/files

### CODE REVIEW

**Comment by matzew** [comment]
are we planning on runnng these on the product repo?

I think we should perhaps just do this on the 1.0 branch. 

for 0.26 we ship the first TP, not even running the e2e tests via Serverless Operator, yet

**Comment by pierDipi** [comment]
I was planning to run post-upgrades tests on the SO repository: https://github.com/openshift-knative/eventing-kafka-broker/pull/59/files#diff-17cfbca086063e05f4fdc318fb48994afc9f01513e371e94f3732edfea4764a5R33

After running post-upgrade tests, the upgrade test does the downgrade and if it passes we're sure the Broker usage doesn't impact these operations of GA things.

> for 0.26 we ship the first TP, not even running the e2e tests via Serverless Operator, yet

Is anything blocking us from running E2E tests?

**Comment by pierDipi** [comment]
I believe the above was the @mgencur's plan too for 1.20

**Comment by matzew** [comment]
Ah, ok - I did not know about the plans for enabling e2e and upgrades on the S-O for 1.20.
But, sure - if @mgencur has capacity for this -> great!

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
