### PR TITLE
[release-1.7] SRVKE-1409: Increase receivers memory request

### PR DESCRIPTION
**Pull request by creydr**
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2950 for [SRVKE-1409](https://issues.redhat.com/browse/SRVKE-1409)

* Increase kafka-broker-receivers memory requests
* Increase kafka-channel-receiver memory requests
* Increase kafka-sink-receiver memory requests

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
You need to rerun `make generate-release RELEASE=v1.7`

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
