### PR TITLE
[1.2] Port - fix RBAC for deletion of configmaps

### PR DESCRIPTION
**Pull request by aliok**
Port https://github.com/knative-sandbox/eventing-kafka-broker/pull/2212

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by aliok** [comment]
/test 49-conformance-aws-ocp-49
/test 49-e2e-aws-ocp-49

```
++ oc get machineset -n openshift-machine-api '' -o 'jsonpath={.status.availableReplicas}'
error: resource name may not be empty
```

**Comment by matzew** [comment]
@aliok we need to run `make RELEASE....` here too 

otherwise we do not get our midstream manifests updated (as these are consumed on the SO repo)

**Pull request closed without merging**
