### PR TITLE
[release-v1.11] Test Keda Kafka Source Scaling (#3491)

### PR DESCRIPTION
**Pull request by Cali0707**
Cherry pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/3491

### CODE REVIEW

**Comment by pierDipi** [comment]
@Cali0707 can you take a look at the failures ?

**Comment by pierDipi** [comment]
Are they related to this change ?

**Comment by Cali0707** [comment]
@pierDipi they are because https://github.com/openshift-knative/eventing-kafka-broker/pull/901 hasn't merged yet

**Comment by Cali0707** [comment]
This commit removes the `DefaultActivationLagThreshold` variable because it's unused, but it only stops being used in #901

**Comment by pierDipi** [comment]
@Cali0707 PR is in now!

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
hmm

```
Exception in thread "contract-file-watcher" Exception in thread "contract-file-watcher" Exception in thread "contract-file-watcher" Exception in thread "contract-file-watcher" java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.HttpServer.updateSSLOptions(io.vertx.core.net.SSLOptions)" because "this.httpsServer" is null
	at dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticle.updateServerConfig(ReceiverVerticle.java:250)
	at dev.knative.eventing.kafka.broker.core.file.FileWatcher.run(FileWatcher.java:148)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.HttpServer.updateSSLOptions(io.vertx.core.net.SSLOptions)" because "this.httpsServer" is null
	at dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticle.updateServerConfig(ReceiverVerticle.java:250)
	at dev.knative.eventing.kafka.broker.core.file.FileWatcher.run(FileWatcher.java:148)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.HttpServer.updateSSLOptions(io.vertx.core.net.SSLOptions)" because "this.httpsServer" is null
	at dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticle.updateServerConfig(ReceiverVerticle.java:250)
	at dev.knative.eventing.kafka.broker.core.file.FileWatcher.run(FileWatcher.java:148)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.HttpServer.updateSSLOptions(io.vertx.core.net.SSLOptions)" because "this.httpsServer" is null
	at dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticle.updateServerConfig(ReceiverVerticle.java:250)
	at dev.knative.eventing.kafka.broker.core.file.FileWatcher.run(FileWatcher.java:148)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by pierDipi** [comment]
```

  Warning  InternalError  32m   consumergroup-controller  failed to initialize consumer group offset: failed to initialize offset: failed to get the topic offsets: dial tcp 10.131.0.15:9092: i/o timeout
```

**Comment by pierDipi** [comment]
```
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  11s (x88 over 33m)  default-scheduler  0/6 nodes are available: 3 Insufficient cpu, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }. preemption: 0/6 nodes are available: 3 No preemption victims found for incoming pod, 3 Preemption is not helpful for scheduling.
```

**Comment by pierDipi** [comment]
PR for adding more nodes https://github.com/openshift-knative/serverless-operator/pull/2486

**Pull request merged**
