### PR TITLE
Consume vertx through quarkus BOM (#2721)

### PR DESCRIPTION
**Pull request by serverless-qe**
* Consume vertx through quarkus BOM

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

* Replace vertx-micrometer-metrics with smallrye ones, reoganize deps

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

* Fix test

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

* Use vertx-micrometer-metrics

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

* Use Quarkus BOM 2.13.5

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by matzew** [comment]
```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /build/vertx-kafka of /build/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project dev.knative.eventing.kafka.broker:data-plane:1.0-SNAPSHOT (/build/pom.xml) has 1 error
[ERROR]     Child module /build/vertx-kafka of /build/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
error: build error: error building at STEP "RUN ./mvnw install -am -DskipTests -Drelease -Dlicense.skip -Deditorconfig.skip --no-transfer-progress": error while running runtime: exit status 1
```

wat?

**Comment by matzew** [comment]
Will PR a change, on the internal / midstream images in a bit (`vertx-kafka` module is missing on the docker files)

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
