### PR TITLE
Remove ansible

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

as per title

### CODE REVIEW

**Comment by pierDipi** [comment]
```
failed to get workingDir: could not fetch source ImageStreamTag: imagestreamtags.image.openshift.io "pipeline:src" not found
```

**Comment by matzew** [comment]
@pierDipi the tests are known to fail, atm (not yet had time for work here)

I merge manually....

**Pull request merged**
