### PR TITLE
[release-v1.11] Add script to run KafkaSource tests with KEDA (#3322)

### PR DESCRIPTION
**Pull request by Cali0707**
Backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/3322

### CODE REVIEW

**Comment by Cali0707** [comment]
@pierDipi should I add a job for this to the midstream CI?

**Comment by pierDipi** [comment]
> @pierDipi should I add a job for this to the midstream CI? If so, where can I find info on how to do that?

To do that you just need to add a command in the Makefile of the branch that matches those regex https://github.com/openshift-knative/hack/blob/32b8e1a2c8724d18ae41dc14c466b53d8b1fc860/config/eventing-kafka-broker.yaml#L40-L43 (or you can add a new one) and then re-run the https://github.com/openshift-knative/hack/actions/workflows/release-generate-ci.yaml workflow

**Pull request merged**
