### PR TITLE
[release-v1.0] Add patches and fix generate release

### PR DESCRIPTION
**Pull request by pierDipi**
See individual commits.

TODO:
- Port this to main and other branches

### CODE REVIEW

**Comment by matzew** [comment]
`update to head` and `create release` are already applying patches 

we need to be careful about that

Patches itself look good !

**Comment by pierDipi** [comment]
> `update to head` and `create release` are already applying patches
> 
> we need to be careful about that
> 
> Patches itself look good !

@matzew done in the last commit

**Review by matzew — APPROVED** [review]
thanks!

/lgtm
/approve

**Pull request merged**
