### PR TITLE
WIP: [release-v1.11]Pem trust webclient options 1.11 with old logger

### PR DESCRIPTION
**Pull request by matzew**
do not merge

### CODE REVIEW

**Comment by matzew** [comment]
```
,"stack_trace":"io.vertx.core.file.FileSystemException: Unable to read file at path '/ocp-serverless-custom-certs/ca-bundle.crt'\n\tat io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1070)\n\tat io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1063)\n\tat io.vertx.core.file.impl.FileSystemImpl.readFileBlocking(FileSystemImpl.java:418)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)\n\tat java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)\n\tat java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)\n\tat java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)\n\tat java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)\n\tat java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:720)\n\tat java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)\n\tat io.vertx.core.net.impl.KeyStoreHelper.loadCA(KeyStoreHelper.java:357)\n\tat io.vertx.core.net.PemTrustOptions.getHelper(PemTrustOptions.java:202)\n\tat io.vertx.core.net.PemTrustOptions.getTrustManagerFactory(PemTrustOptions.java:168)\n\tat io.vertx.core.net.impl.SSLHelper.lambda$build$6(SSLHelper.java:250)\n\tat io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)\n\tat io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)\n\tat io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: java.io.IOException: Is a directory\n\tat java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)\n\tat java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)\n\tat java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)\n\tat java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)\n\tat java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)\n\tat java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:232)\n\tat java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)\n\tat java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)\n\tat java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)\n\tat java.base/java.nio.file.Files.read(Files.java:3244)\n\tat java.base/java.nio.file.Files.readAllBytes(Files.java:3295)\n\tat io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1067)\n\t... 23 common frames omitted\n","context":{},"target":"http://logger-pod.eventing-e2e1.svc.cluster.local"}
{"@timestamp":"2023-12-15T12:02:38.149Z","@version":"1","message":"failed to send event to subscriber context={topics=[knative-broker-eventing-e2e0-broker], consumerGroup='knative-trigger-eventing-e2e0-trigger', reference=uuid: \"a4cbe6e8-32ef-4a09-8bed-5de541b8c6db\"\nnamespace: \"eventing-e2e0\"\nname: \"trigger\"\n} target=http://logger-pod.eventing-e2e0.svc.cluster.local","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.impl.http.WebClientCloudEventSender","thread_name":"vert.x-worker-thread-6","level":"ERROR","level_value":40000,"stack_trace":"io.vertx.core.file.FileSystemException: Unable to read file at path '/ocp-serverless-custom-certs/ca-bundle.crt'\n\tat io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1070)\n\tat io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:1063)\n\tat io.vertx.core.file.impl.FileSystemImpl.readFileBlocking(FileSystemImpl.java:418)\n\tat java.base/java.util.stream.ReferencePipeli
```

**Comment by pierDipi** [comment]
Apparently `/ocp-serverless-custom-certs/ca-bundle.crt`

```
Is a directory
```

**Comment by matzew** [comment]
yeah, I am double checking that now :-)

**Pull request closed without merging**
