### PR TITLE
[release-v1.14] Clientpool fixes

### PR DESCRIPTION
**Pull request by Cali0707**
This PR backports https://github.com/knative-extensions/eventing-kafka-broker/pull/4001 and https://github.com/knative-extensions/eventing-kafka-broker/pull/4005 to fix issues with kafka connection pooling

### CODE REVIEW

**Comment by pierDipi** [comment]
```
reason": "cannot obtain Kafka cluster admin, kafka: client has run out of available brokers to talk to: dial tcp: lookup my-cluster-kafka-bootstrap.kafka on 172.30.0.10:53: no such host",
```

**Comment by Cali0707** [comment]
> ```
> reason": "cannot obtain Kafka cluster admin, kafka: client has run out of available brokers to talk to: dial tcp: lookup my-cluster-kafka-bootstrap.kafka on 172.30.0.10:53: no such host",
> ```

Uh oh, that doesn't look great - do you think this is us having too many connections still @pierDipi ?

**Pull request merged**
