### PR TITLE
Align EKB and eventing-core installed versions for e2e tests

### PR DESCRIPTION
**Pull request by creydr**
Align the installed version of EKB and eventing-core for tests.

Make use of `USE_RELEASE_NEXT` and `make generated-files-release-next` from https://github.com/openshift-knative/serverless-operator/pull/2528

Testrun in #1026 and #994

### CODE REVIEW

**Comment by pierDipi** [comment]
@creydr @mgencur in this form, we would only support release next, I believe if we make the branch/version configurable instead of hardcoding release-next in SO ( and default it to use project.yaml configurations) we could leverage it in any branch

**Comment by mgencur** [comment]
> @creydr @mgencur in this form, we would only support release next, I believe if we make the branch/version configurable instead of hardcoding release-next in SO ( and default it to use project.yaml configurations) we could leverage it in any branch

Not sure if I understand it correctly. You mean we could use `make generated-files` instead switching between `generated-files-release-next` an `make generated-files` by allowing to pass the branch [here](https://github.com/openshift-knative/serverless-operator/pull/2528/files#diff-21a12bc776379d1caf0e8df5831198a8b32f6a51adcf382a5bff6421fbdd05c2R34) ?
Something like `KNATIVE_EVENTING_KAFKA_BROKER_BRANCH=release-next make generated-files` ?

**Comment by creydr** [comment]
In this PR we would only install the release-next artifacts, when on the release-next branch. Otherwise the artifacts of the coresponding release-vX.Y branch will be installed (see https://github.com/openshift-knative/eventing-kafka-broker/blob/679967d564c63f15fe295f4f86060ef85d1013f6/openshift/e2e-common.sh#L92-L101).

Anyhow we discussed that something like this would make more sense to have it directly in SO, so we don't need to repeat it in every repo. So closing this here

**Pull request closed without merging**
