### PR TITLE
[release-v1.9] Remove unschedulable pods marking during eviction

### PR DESCRIPTION
**Pull request by pierDipi**
This is racing with the autoscaler, so we cannot really
mark pods as unschedulable.

I think this was an early optimization to avoid many
rescheduling because the risk is that we end up rescheduling
many consumer, however, to mitigate this we can also think about
increasing the "scale down refresh period" so that we don't
scale up / down for at least that time window.

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
Done in https://github.com/openshift-knative/eventing-kafka-broker/pull/808

**Pull request closed without merging**
