### PR TITLE
Remove OCP bundle patch

### PR DESCRIPTION
**Pull request by creydr**
Fixes the current Jenkins issues: https://master-jenkins-csb-serverless-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci/job/knative-nightly-ci-eventing-kafka-broker/818/console

### CODE REVIEW

**Comment by pierDipi** [comment]
@creydr I think we can completely remove that patch since now we're using the Knative built-in mechanism to inject trust bundles

**Comment by matzew** [comment]
@pierDipi oh, that would b actually super

**Comment by creydr** [comment]
removed

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
