### PR TITLE
[release-v1.15] Add LICENSE file to Java static-images

### PR DESCRIPTION
**Pull request by creydr**
Adding the LICENSE file in the static images (similar to #1360).

### CODE REVIEW

**Comment by creydr** [comment]
```
        "passed": [
            {
                "name": "HasLicense",
                "elapsed_time": 0,
                "description": "Checking if terms and conditions applicable to the software including open source licensing information are present. The license must be at /licenses"
            },
```

**Review by pierDipi — COMMENTED** [review]
Only for hermetic is really needed

**Comment by creydr** [comment]
build server is having issues ATM :/

**Comment by creydr** [comment]
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-dispatcher-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-event-display-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-heartbeats-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-kafka-controller-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-migrate-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-post-install-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-receiver-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-committed-offset-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-consumer-group-lag-provider-test-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-event-sender-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-eventshub-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-kafka-consumer-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-logs-exporter-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-print-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-recordevents-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-request-sender-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-watch-cm-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-wathola-fetcher-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-wathola-forwarder-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-wathola-receiver-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-test-wathola-sender-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / kn-ekb-webhook-kafka-115"
/override "Red Hat Konflux / serverless-operator-135-enterprise-contract / pr group add-license-to-java-images"

**Pull request merged**
