### PR TITLE
Increase poll.timeout from 2 to 8 minutes

### PR DESCRIPTION
**Pull request by mgencur**
Example failure which should be fixed by this change is [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-main-ocp4.15-lp-interop-operator-e2e-interop-aws-ocp415/1726481336161538048)

Also run go get -u knative.dev/reconciler-test && ./hack/update-deps.sh and make generate-release

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
Please run `make generate-release`

**Comment by mgencur** [comment]
/hold
We can try a proper fix for https://issues.redhat.com/browse/SRVKE-1536 before increasing the timeouts. cc @Cali0707

**Comment by maschmid** [comment]
/test 411-test-reconciler-aws-ocp-411

infra

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
