### PR TITLE
[release-v1.4] `pod.Status.Phase == apiv1.PodRunning` is not a good way to test if pods are Running

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2523

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by aliok** [comment]
/hold

Until https://github.com/knative-sandbox/eventing-kafka-broker/pull/2523 is merged

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
