### PR TITLE
[release-v1.0] Just do one receiver

### PR DESCRIPTION
**Pull request by matzew**
Following up on:
https://github.com/openshift/release/pull/26136

as for just one receiver image

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

/cherry-pick release-1.1

**Comment by matzew** [comment]
@pierDipi this is already in 1.1:
https://github.com/openshift-knative/eventing-kafka-broker/tree/release-v1.1/openshift/ci-operator/knative-images

and 1.2:
https://github.com/openshift-knative/eventing-kafka-broker/tree/release-v1.2/openshift/ci-operator/knative-images

No need to cherry pick

**Pull request merged**
