### PR TITLE
[release-v1.11] Revert 'logger bump' backport from upstream/main and go to latest 1.2.x logback

### PR DESCRIPTION
**Pull request by matzew**
This reverts commit a0c2dea9f1dc69b13140c1eef524984926be556e **_AND_** goes to latest of `1.2.x` of logback

### CODE REVIEW

**Comment by matzew** [comment]
The failed test, now has the structured logger back: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_eventing-kafka-broker/938/pull-ci-openshift-knative-eventing-kafka-broker-release-v1.11-411-test-reconciler-aws-ocp-411/1742924060653785088/artifacts/test-reconciler-aws-ocp-411/openshift-gather-extra/artifacts/pods/knative-eventing_kafka-broker-dispatcher-6964d94c7c-5lx6s_kafka-broker-dispatcher.log

**Comment by matzew** [comment]
/hold

let's see if this also keeps the logs

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
Log is here as well:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-knative_eventing-kafka-broker/938/pull-ci-openshift-knative-eventing-kafka-broker-release-v1.11-414-test-reconciler-aws-ocp-414/1744323535528005632/artifacts/test-reconciler-aws-ocp-414/openshift-gather-extra/artifacts/pods/knative-eventing_kafka-broker-dispatcher-8dcb45cc8-2kffr_kafka-broker-dispatcher.log

/retest

**Pull request merged**
