### PR TITLE
[release-v1.11] Test TLS and KEDA jobs

### PR DESCRIPTION
**Pull request by pierDipi**

### CODE REVIEW

**Review by Cali0707 — APPROVED** [review]
/lgtm

Thanks for fixing this @pierDipi !!

**Comment by dsimansk** [comment]
@pierDipi @Cali0707 a clean rebase would help?

how does it relate to S-O release branch cut?

**Comment by pierDipi** [comment]
https://github.com/openshift-knative/serverless-operator/pull/2490

**Comment by dsimansk** [comment]
/approve
/lgtm

🤞

**Comment by pierDipi** [comment]
```
{"@timestamp":"2024-02-13T14:03:28.003Z","@version":"1","message":"Failed to initialize a channel. Closing: [id: 0x1b78cd96, L:/10.128.2.33:8443 - R:/10.128.2.34:54236]","logger_name":"io.netty.channel.ChannelInitializer","thread_name":"vert.x-eventloop-thread-0","level":"WARN","level_value":30000,"stack_trace":"java.lang.NullPointerException: Cannot invoke \"io.vertx.core.net.impl.SslContextUpdate.sslChannelProvider()\" because the return value of \"io.vertx.core.Future.result()\" is null\n\tat io.vertx.core.net.impl.TCPServerBase.lambda$listen$6(TCPServerBase.java:240)\n\tat io.vertx.core.net.impl.ServerChannelLoadBalancer.initChannel(ServerChannelLoadBalancer.java:61)\n\tat io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)\n\tat io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)\n\tat io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)\n\tat io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)\n\tat io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)\n\tat io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)\n\tat io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)\n\tat io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n"}
```

**Comment by pierDipi** [comment]
TLS tests now are green @dsimansk @matzew @Cali0707

**Comment by pierDipi** [comment]
Anyone LGTM this one so that we can rebase on run the tests on https://github.com/openshift-knative/eventing-kafka-broker/pull/957

**Review by Cali0707 — APPROVED** [review]
/lgtm

**Pull request merged**
