### PR TITLE
[release-v1.5] Use AllowRestrictedPodSecurityStandard in vendored creation.go

### PR DESCRIPTION
**Pull request by mgencur**
Add remaining vendor changes from https://github.com/openshift/knative-eventing/commit/6ea60fb516fc80f5db539e8ef68c1b95abe50036

### CODE REVIEW

**Comment by mgencur** [comment]
@pierDipi Apologies for this forgotten change.

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
