### PR TITLE
[release-v1.2] Add services to controller cluster role 

### PR DESCRIPTION
**Pull request by pierDipi**
Part of https://github.com/openshift-knative/serverless-operator/pull/1527 and Matthias's thread on Slack

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
/retest-required

```
{  "e2e-aws-ocp-410" test steps failed: "e2e-aws-ocp-410" pod "e2e-aws-ocp-410-test" failed: the pod ci-op-j1i9gi96/e2e-aws-ocp-410-test failed after 1h22m34s (failed containers: test): ContainerFailed one or more containers exited
```

Perhaps a container in knative-eventing namespace is coming up?

**Comment by matzew** [comment]
Wonder why this does not go in :-(

**Comment by matzew** [comment]
some `error creating buildah builder`

**Comment by matzew** [comment]
... error creating buildah builder


/retest

**Comment by matzew** [comment]
/retest

buildah

**Comment by matzew** [comment]
/retest
/retest

GO IN!!!!! 11!!!

**Comment by aliok** [comment]
/test 410-images

```
error: build error: error creating build container: initializing source docker://image-registry.openshift-image-registry.svc:5000/ci-op-jf5g9tsp/pipeline@sha256:4250fa7c9aa6517cc7145839247a6d70f3fe4d5df72ed91767ee0edc6538affa: pinging container registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp: lookup image-registry.openshift-image-registry.svc on 172.30.0.10:53: no such host
```

**Comment by pierDipi** [comment]
```
error: build error: error creating build container: initia...penshift-image-registry.svc on 172.30.0.10:53: no such host 
```
/test 410-images

**Comment by aliok** [comment]
/retest

```
Trying to pull image-registry.openshift-image-registry.svc:5000/ci-op-4r9v59dd/pipeline@sha256:aa9ba17502f6c1d1fe6587ef9275437fa51030ec5a3981704d8bcb7a5f51af92...
error: error creating buildah builder: initializing source docker://image-registry.openshift-image-registry.svc:5000/ci-op-4r9v59dd/pipeline@sha256:aa9ba17502f6c1d1fe6587ef9275437fa51030ec5a3981704d8bcb7a5f51af92: pinging container registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp: i/o timeout
```

**Comment by matzew** [comment]
/close

most of this was merged in here:
https://github.com/openshift-knative/eventing-kafka-broker/pull/230

**Pull request closed without merging**
