### PR TITLE
Change from Beta to GA (#3722)

### PR DESCRIPTION
**Pull request by serverless-qe**
This component is GA.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by creydr** [comment]
`received unexpected HTTP status: 502 Bad Gateway`
/test 412-test-reconciler-keda-aws-412

**Comment by creydr** [comment]
` build error: creating build container: copying syst...1-runtime: received unexpected HTTP status: 502 Bad Gateway `
/retest

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
The `test-reconciler` fails, as:

```
FAIL: test/e2e_new TestBrokerEventTypeAutoCreate/AutoCreateEventTypesOnBroker/Assert/broker_create_event_type (480.02s)
    eventtype.go:75: failed to verify eventtype test EventTypes ready and test eventtypes match or not timed out waiting for the condition: <nil>
        &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:188251 Continue: RemainingItemCount:<nil>} Items:[]}
```

is that a flake, @Cali0707 ?

/test 414-test-reconciler-aws-414

**Comment by creydr** [comment]
> The `test-reconciler` fails, as:
> 
> ```
> FAIL: test/e2e_new TestBrokerEventTypeAutoCreate/AutoCreateEventTypesOnBroker/Assert/broker_create_event_type (480.02s)
>     eventtype.go:75: failed to verify eventtype test EventTypes ready and test eventtypes match or not timed out waiting for the condition: <nil>
>         &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:188251 Continue: RemainingItemCount:<nil>} Items:[]}
> ```
> 
> is that a flake, @Cali0707 ?
> 
> /test 414-test-reconciler-aws-414

Addressed in https://github.com/openshift-knative/eventing-kafka-broker/pull/1028

**Comment by creydr** [comment]
```
ERROR: timeout waiting for secret kafka/my-sasl-user to exist
```

/test 414-test-reconciler-aws-414

**Comment by creydr** [comment]
```
ERROR: timeout waiting for secret kafka/my-sasl-user to exist
```
/retest

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
