### PR TITLE
Update eventing nightly (#3972)

### PR DESCRIPTION
**Pull request by serverless-qe**
bumping knative.dev/eventing 96c30bd...fe6bd56:
  > fe6bd56 Adding symbolic link for event policy type.  (# 8081)
  > 2f1f866 fix: trigger labels are set properly with cn event links enabled (# 8066)
  > 5f6713a fix(test): creating the knsubscribe clusterrolebinding does not cause install script to fail (# 8068)
  > 8e039dd Watch only our own OIDC-related secrets (# 8070)
  > 5a96619 Add Kubernetes Version Check to Installation Script (# 8025)
  > 332d974 Update TokenVerifier to verify AuthZ too (# 8063)
  > 3264b21 List applying EventPolicies in Brokers status (# 8060)
  > 657c3cd List applying policies in job sink (# 8064)
  > 98ed09c [main] Update community files (# 8069)
  > e2d782f # 7879: Changes to add filters field (# 7930)
  > d18595f :bug: Codecov reject any coverage drop (# 8065)
  > 399bb86 Reconcile EventPolicies when features configmap changes (# 8059)
  > 4f2b53f Set APIVersion and Kind of EventPolicy manually in OwnerReference of backing channels policy (# 8031)

Signed-off-by: Knative Automation <automation@knative.team>

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/retest

**Comment by pierDipi** [comment]
```
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2024-07-30T02:43:17Z",
                        "message": "containers with unready status: [kafka-broker-dispatcher kube-rbac-proxy]",
                        "reason": "ContainersNotReady",
                        "status": "False",
                        "type": "ContainersReady"
                    },
```

**Comment by pierDipi** [comment]
```
W0730 02:43:16.690117       1 reflector.go:539] knative.dev/pkg/controller/controller.go:726: failed to list *v1alpha1.EventPolicy: the server could not find the requested resource (get eventpolicies.eventing.knative.dev)
E0730 02:43:16.690239       1 reflector.go:147] knative.dev/pkg/controller/controller.go:726: Failed to watch *v1alpha1.EventPolicy: failed to list *v1alpha1.EventPolicy: the server could not find the requested resource (get eventpolicies.eventing.knative.dev)
```
in kafka-controller

**Comment by pierDipi** [comment]
```
Job.batch "storage-version-migration-eventing-eventing-knative-nightly-1.34.0" is invalid: spec.template.labels: Invalid value: "storage-version-migration-eventing-eventing-knative-nightly-1.34.0": must be no more than 63 characters
```

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
