### PR TITLE
[v1.2] Prober targets service instead of pods directly (#2112)

### PR DESCRIPTION
**Pull request by pierDipi**
See commit for reference upstream PR

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by pierDipi** [comment]
After this one, I'll cherry pick https://github.com/knative-sandbox/eventing-kafka-broker/pull/2164/files

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
@pierDipi perhap we do https://github.com/openshift-knative/eventing-kafka-broker/pull/249 first?

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
