### PR TITLE
[1.4] Proper webhook backport

### PR DESCRIPTION
**Pull request by aliok**
Backport https://github.com/knative-sandbox/eventing-kafka-broker/pull/2626

### CODE REVIEW

**Comment by aliok** [comment]
/hold

Waiting for https://github.com/knative-sandbox/eventing-kafka-broker/pull/2626

**Comment by aliok** [comment]
/unhold

https://github.com/knative-sandbox/eventing-kafka-broker/pull/2626 is in

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
This is backported to upstream 1.5: https://github.com/knative-sandbox/eventing-kafka-broker/pull/2632

**Pull request merged**
