### PR TITLE
[release-v1.2] Adding secret finalizer

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2346

### CODE REVIEW

**Comment by matzew** [comment]
/test 49-e2e-aws-ocp-49

infra...

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
> > /cherry-pick release-v1.3
> 
> that does not work, b/c of the `make RELEASE` (I ave a PR for that already open)

it worked https://github.com/openshift-knative/eventing-kafka-broker/pull/318 :partying_face:

**Pull request merged**
