### PR TITLE
[release-v1.3] Channel services cluster role (#230)

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/commit/aeee47f5983128437ffb47958910d88d4371b2a1

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
oh.. the forgotten backports :hear_no_evil:

**Comment by matzew** [comment]
infra

/retest

**Comment by pierDipi** [comment]
passed on 4.10

**Pull request merged**
