### PR TITLE
[main] Reuse github action for building multiarch test images

### PR DESCRIPTION
**Pull request by mgencur**
Part of https://issues.redhat.com/browse/SRVCOM-2053
(sibling of https://github.com/openshift-knative/eventing-kafka-broker/pull/419)

* Reuses github action from https://github.com/openshift-knative/hack/pull/3
* Modifies create-release-branch.sh script to copy the github action.
* Also combines changes from the following PRs:
** https://github.com/openshift-knative/eventing-kafka-broker/pull/326
** https://github.com/openshift-knative/eventing-kafka-broker/pull/417

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by mgencur** [comment]
@pierDipi Thanks, pushed. Also, to the other PR: https://github.com/openshift-knative/eventing-kafka-broker/pull/419

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
