### PR TITLE
[release-v1.3] Remove config-tracing ConfigMap

### PR DESCRIPTION
**Pull request by pierDipi**
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by matzew** [comment]
Now, on this branch, run `make RELEASE=v1.3.2 generate-release` again...

you will get an error, like:

```
rm: cannot remove 'control-plane/config/eventing-kafka-broker/200-controller/100-config-tracing.yaml': No such file or directory
make: *** [Makefile:72: generate-release] Error 1
```

I tried these kind of things before...  I guess, we just have to check in the removal of the CP config file, and not touch the script :shrug:

**Comment by pierDipi** [comment]
Ah I will add the -rf flag

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
