### PR TITLE
[release-v1.3] Switch back to use SO main branch

### PR DESCRIPTION
**Pull request by pierDipi**
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
```
The connection to the server api.ci-ocp-4-9-amd64-aws-us-west-1-rkmq8.hive.aws.ci.openshift.org:6443 was refused - did you specify the right host or port?
```
/retest

**Comment by matzew** [comment]
merging...

**Pull request merged**
