### PR TITLE
[release-v1.2] Remove KafkaSource migration logic

### PR DESCRIPTION
**Pull request by pierDipi**
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
@pierDipi hrm, looks like here we had (on 4.9) an `TestKafkaSourceUpdate` issue

**Comment by pierDipi** [comment]
That's a flake but I don't think it's related to this change.

**Pull request merged**
