### PR TITLE
[release-1.10] Bump reconciler-test to latest commit of release-1.10

### PR DESCRIPTION
**Pull request by ReToCode**
# Changes
- Incorporate https://github.com/knative-extensions/reconciler-test/pull/565

Left/right should be fine this time...

/assign @pierDipi

### CODE REVIEW

**Comment by ReToCode** [comment]
@pierDipi what about the other changes like `vendor/knative.dev/reconciler-test/pkg/images/ko/publish.go`. Are they ok or should I drop them?

**Comment by pierDipi** [comment]
did you run `make generate-release`?

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
