### PR TITLE
[release-v1.2] KafkaSource lease remapping (#155)

### PR DESCRIPTION
**Pull request by pierDipi**
Like https://github.com/openshift-knative/eventing-kafka-broker/pull/155 but for 1.2

The changes in the vendor directory are due to the copy we did from 1.1 but we're now on a different branch, so they are expected.

### CODE REVIEW

**Comment by pierDipi** [comment]
```
ERRO[2022-03-18T15:35:23Z] Some steps failed:                           
ERRO[2022-03-18T15:35:23Z] 
  * could not run steps: step [release:latest-conformance-aws-ocp-49] failed: failed to get CLI image: unable to wait for the 'cli' image in the stable stream to populate (waited for 31.048334075s): timed out waiting for the condition 
  
```
flake?
/retest

**Comment by matzew** [comment]
/hold

the 1.2 still needs some help (on it, somewhat :see_no_evil: )

**Comment by pierDipi** [comment]
> /hold
> 
> the 1.2 still needs some help (on it, somewhat see_no_evil )

It's what I'm doing in this PR

**Comment by matzew** [comment]
> It's what I'm doing in this PR

ok - hehe. the title was misleading. 

I really hope for 1.3 we can go to a "normal" midstream branch creation

**Comment by pierDipi** [comment]
blocked by https://github.com/openshift-knative/eventing-kafka-broker/pull/160

**Comment by aliok** [comment]
#160 is merged @pierDipi . This needs rebase

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
