### PR TITLE
[release-v1.15] Fix e2e tests

### PR DESCRIPTION
**Pull request by pierDipi**

### CODE REVIEW

**Comment by pierDipi** [comment]
hmm, there is nothing in the [must-gathers](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-knative_eventing-kafka-broker/1164/pull-ci-openshift-knative-eventing-kafka-broker-release-v1.15-415-test-reconciler-encryption-auth-aws-415/1830927441405677568/artifacts/test-reconciler-encryption-auth-aws-415/) for [this run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-knative_eventing-kafka-broker/1164/pull-ci-openshift-knative-eventing-kafka-broker-release-v1.15-415-test-reconciler-encryption-auth-aws-415/1830927441405677568)

**Comment by maschmid** [comment]
The reconciler job https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-knative_eventing-kafka-broker/1164/pull-ci-openshift-knative-eventing-kafka-broker-release-v1.15-415-test-reconciler-aws-415/1830927441384706048  only scales to 4

> SCALE_UP=4 INSTALL_SERVING="false" INSTALL_KAFKA="true" ./hack/install.sh` 

We normally run EKB tests with 6 workers (see https://github.com/openshift-knative/serverless-operator/blob/main/Makefile#L187  )  , so we should probably increase it, if we're not scaling it up elsewhere...

**Comment by pierDipi** [comment]
for the TLS test

```
    certificate.go:165: Failed to get certificate knative-eventing/kafka-broker-ingress-server-tls: certificates.cert-manager.io "kafka-broker-ingress-server-tls" not found
```

**Review by creydr — APPROVED** [review]
/lgtm

**Pull request merged**
