### PR TITLE
[release-v1.4] Knative error extensions (#2374)

### PR DESCRIPTION
**Pull request by matzew**
backport

### CODE REVIEW

**Review by aliok — APPROVED** [review]
/lgtm
/approve

Looks identical!

**Comment by matzew** [comment]
```
  *[2022-08-23T15:45:01Z]NoClusters: No clusters in pool are ready to be claimed 
```

**Comment by matzew** [comment]
```
  *[2022-08-24T12:38:06Z]NoClusters: No clusters in pool are ready to be claimed 
```

/retest

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
