### PR TITLE
[release-v1.1] Poll for new records when `max.poll.records` limit isn't reached (#2003)

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick https://github.com/knative-sandbox/eventing-kafka-broker/commit/84ab89b7eba5e130b2b4d576a042e1487f93a53e

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
Trying to rebase https://github.com/openshift-knative/eventing-kafka-broker/pull/156

/cherry-pick release-v1.2

**Pull request merged**
